services:
  api_catalog:
    build: .
    container_name: api_catalog
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=postgres
    links:
      - postgres
    networks:
      - microservices-network

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=filmesdb
    networks:
      - microservices-network

networks:
  microservices-network:
    name: microservices-network
