services:
  api_catalog:
    build: .
    container_name: api_catalog
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres
    links:
      - postgres
    networks:
      - microservices-network

  postgres:
    image: postgres:13
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=filmesdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

networks:
  microservices-network:
    name: microservices-network
